/**
 * Root layout file for the Next.js application.
 * This file defines the overall structure of the webpage, including the HTML and body elements.
 * It uses the `children` prop to inject the main content of the page.
 * This layout is applied globally across all pages in the app.
 */

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* The body of the page where the content of each specific page is rendered */}
      <body>{children}</body>
    </html>
  )
}